baseURL = "https://mtthw.xyz/"
locale = "en-IE"
title = "mtthw.xyz"

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  taxonomy = ["HTML", "JSON"]
  term = ["HTML", "JSON"]
